FROM java:8-jre
WORKDIR /usr/src
ENV MYSQL_HOST=localhost
ENV MYSQL_DATABASE=foodie_db
ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=root
ENV MYSQL_CI_URL=jdbc:mysql://localhost:3306/foodie_db
ADD ./target/Server-1.0.jar /usr/src/Server-1.0.jar
ENTRYPOINT ["java", "-jar", "Server-1.0.jar"]
